# Generated by Django 5.2.3 on 2025-07-16 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtg_blog', '0002_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
