# Generated by Django 5.2.3 on 2025-08-08 18:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtg_blog', '0003_alter_topic_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Your full name', max_length=100)),
                ('email', models.EmailField(help_text='Your email address', max_length=254)),
                ('image', models.ImageField(help_text='Upload your contest photo', upload_to='contest_photos/')),
                ('submission_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time of submission')),
            ],
            options={
                'verbose_name': 'Photo Submission',
                'verbose_name_plural': 'Photo Submissions',
                'ordering': ['-submission_date'],
            },
        ),
    ]
