# Generated by Django 5.2.3 on 2025-08-08 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mtg_blog', '0004_photosubmission'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photosubmission',
            old_name='image',
            new_name='photo',
        ),
    ]
